// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1tgjHSQDFJvhZVd7T4RA5fg1o9OFwElg',
    appId: '1:1055922543089:web:dace0c909446d1a1660c50',
    messagingSenderId: '1055922543089',
    projectId: 'reminderlogin-ae2a4',
    authDomain: 'reminderlogin-ae2a4.firebaseapp.com',
    storageBucket: 'reminderlogin-ae2a4.firebasestorage.app',
    measurementId: 'G-MZW0S807D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC113p2QdrAOsK6OANGOpKwDkLbjuNdFIU',
    appId: '1:1055922543089:android:ec1110a07b6daeaf660c50',
    messagingSenderId: '1055922543089',
    projectId: 'reminderlogin-ae2a4',
    storageBucket: 'reminderlogin-ae2a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOoXoweXLXZOhAImCwmxmijgy1_RJuzVE',
    appId: '1:1055922543089:ios:af8a40642fe2da8f660c50',
    messagingSenderId: '1055922543089',
    projectId: 'reminderlogin-ae2a4',
    storageBucket: 'reminderlogin-ae2a4.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminder191224',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOoXoweXLXZOhAImCwmxmijgy1_RJuzVE',
    appId: '1:1055922543089:ios:af8a40642fe2da8f660c50',
    messagingSenderId: '1055922543089',
    projectId: 'reminderlogin-ae2a4',
    storageBucket: 'reminderlogin-ae2a4.firebasestorage.app',
    iosBundleId: 'com.example.medicineReminder191224',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1tgjHSQDFJvhZVd7T4RA5fg1o9OFwElg',
    appId: '1:1055922543089:web:ea4f64340b2ddd3d660c50',
    messagingSenderId: '1055922543089',
    projectId: 'reminderlogin-ae2a4',
    authDomain: 'reminderlogin-ae2a4.firebaseapp.com',
    storageBucket: 'reminderlogin-ae2a4.firebasestorage.app',
    measurementId: 'G-8VZ86M6Y0Q',
  );
}
